### ISSUE TITLE
It does not work with 4.3

### ISSUE THREAD

**Issue by gerroon** [xiaocai-laoniao/DarkProcessingTheme_4.0#1]
Hi

Installled in Windows 11 Processing 4.3 as explained in the read. It does not seem to work :( I still get the standard theme

**Comment by hendasheng** [comment]
+1

**Comment by dabing1022** [comment]
> Hi
> 
> Installled in Windows 11 Processing 4.3 as explained in the read. It does not seem to work :( I still get the standard theme

It is recommended to use the "Theme Selector" tool for greater flexibility and enhanced power
